---
- name: Trabajar con ficheros
  hosts: all
      
  tasks:
  - name: Crear un fichero vacío
    file:
      path: "/tmp/awx-prueba.txt"
      state: "touch"
  - name: mostrando variable
    debug: 
      msg: {{ var_ejemplo }}


...
